import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor configuration for the Sidekick native shell.
 *
 * Loading model (local-asset shell, changed 2026-06-09):
 *   The WebView serves the app's ASSETS locally from the bundled
 *   `mobile/webdir/` (capacitor://localhost) for a native-fast cold
 *   boot — no network round-trip to download JS/CSS. Only SERVER API
 *   calls go to the remote host (resolved by `src/apiBase.ts`).
 *
 *   Launch entry is `mobile/webdir/index.html` — a tiny self-contained
 *   host-picker. On first launch (no saved URL) it prompts for the
 *   proxy host, validates it, saves it in localStorage, then navigates
 *   to the LOCAL `./app.html` (the real app). On subsequent launches it
 *   loads `./app.html` immediately (no probe) so cold boot never waits
 *   on the network. The app reaches the saved host via apiBase; if the
 *   host is down it surfaces a dismissible in-app reconnect prompt
 *   (src/reconnectModal.ts) rather than bouncing back to the picker.
 *
 *   Build: `npm run build:cap` compiles src/ then populates webdir with
 *   app.html + build/ + styles/ + assets/ + manifest.json + sw.js.
 *   Frontend changes now require a fresh asset bundle (re-run build:cap
 *   + `npx cap copy` + Xcode rebuild) — the live-server dev-reload path
 *   no longer applies in this shell.
 *
 *   To re-pick the host later, navigate to
 *   `capacitor://localhost/?config=1` (forces the picker form). Because
 *   the app's own origin is now capacitor://localhost, this is a plain
 *   same-origin navigation.
 *
 * `allowNavigation: ['*']` is retained as a permissive default; the
 * app stays on capacitor://localhost and reaches hosts via CORS fetch.
 *
 * Layout:
 *   mobile/ios/      — Xcode project
 *   mobile/android/  — Gradle project
 *   mobile/webdir/   — host-picker (index.html, committed) + bundled app
 *                      (app.html + assets, generated by build:cap)
 * The capacitor.config.ts itself stays at repo root because the
 * Capacitor CLI looks for it there with no override.
 */

const config: CapacitorConfig = {
  appId: 'com.reimaginerobotics.sidekick',
  appName: 'Sidekick',
  webDir: 'mobile/webdir',
  ios: { path: 'mobile/ios' },
  android: { path: 'mobile/android' },
  server: {
    cleartext: false,
    allowNavigation: ['*'],
  },
};

export default config;
