// AUTO-GENERATED by scripts/fetch-openrouter-capabilities.mjs.
// Do NOT edit by hand — re-run the script to refresh.
// Source: https://openrouter.ai/api/v1/models
// Fetched: 2026-05-01T17:16:52.193Z
// Only models with non-text input modalities are included; missing
// IDs default to text-only at the call site.
export const FETCHED_AT = '2026-05-01T17:16:52.193Z';

export const MODEL_MODALITIES: Record<string, readonly string[]> = {
  "x-ai/grok-4.3": [
    "text",
    "image"
  ],
  "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": [
    "text",
    "audio",
    "image",
    "video"
  ],
  "~anthropic/claude-haiku-latest": [
    "image",
    "text"
  ],
  "~openai/gpt-mini-latest": [
    "file",
    "image",
    "text"
  ],
  "~google/gemini-pro-latest": [
    "audio",
    "file",
    "image",
    "text",
    "video"
  ],
  "~moonshotai/kimi-latest": [
    "text",
    "image"
  ],
  "~google/gemini-flash-latest": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "~anthropic/claude-sonnet-latest": [
    "text",
    "image"
  ],
  "~openai/gpt-latest": [
    "file",
    "image",
    "text"
  ],
  "qwen/qwen3.5-plus-20260420": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.6-flash": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.6-35b-a3b": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.6-27b": [
    "text",
    "image",
    "video"
  ],
  "openai/gpt-5.5-pro": [
    "file",
    "image",
    "text"
  ],
  "openai/gpt-5.5": [
    "file",
    "image",
    "text"
  ],
  "xiaomi/mimo-v2.5": [
    "text",
    "audio",
    "image",
    "video"
  ],
  "openai/gpt-5.4-image-2": [
    "image",
    "text",
    "file"
  ],
  "~anthropic/claude-opus-latest": [
    "text",
    "image"
  ],
  "baidu/qianfan-ocr-fast:free": [
    "image",
    "text"
  ],
  "moonshotai/kimi-k2.6": [
    "text",
    "image"
  ],
  "anthropic/claude-opus-4.7": [
    "text",
    "image"
  ],
  "anthropic/claude-opus-4.6-fast": [
    "text",
    "image"
  ],
  "google/gemma-4-26b-a4b-it:free": [
    "image",
    "text",
    "video"
  ],
  "google/gemma-4-26b-a4b-it": [
    "image",
    "text",
    "video"
  ],
  "google/gemma-4-31b-it:free": [
    "image",
    "text",
    "video"
  ],
  "google/gemma-4-31b-it": [
    "image",
    "text",
    "video"
  ],
  "qwen/qwen3.6-plus": [
    "text",
    "image",
    "video"
  ],
  "z-ai/glm-5v-turbo": [
    "image",
    "text",
    "video"
  ],
  "x-ai/grok-4.20-multi-agent": [
    "text",
    "image",
    "file"
  ],
  "x-ai/grok-4.20": [
    "text",
    "image",
    "file"
  ],
  "google/lyria-3-pro-preview": [
    "text",
    "image"
  ],
  "google/lyria-3-clip-preview": [
    "text",
    "image"
  ],
  "rekaai/reka-edge": [
    "image",
    "text",
    "video"
  ],
  "xiaomi/mimo-v2-omni": [
    "text",
    "audio",
    "image",
    "video"
  ],
  "openai/gpt-5.4-nano": [
    "file",
    "image",
    "text"
  ],
  "openai/gpt-5.4-mini": [
    "file",
    "image",
    "text"
  ],
  "mistralai/mistral-small-2603": [
    "text",
    "image"
  ],
  "bytedance-seed/seed-2.0-lite": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.5-9b": [
    "text",
    "image",
    "video"
  ],
  "openai/gpt-5.4-pro": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-5.4": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-5.3-chat": [
    "text",
    "image",
    "file"
  ],
  "google/gemini-3.1-flash-lite-preview": [
    "text",
    "image",
    "video",
    "file",
    "audio"
  ],
  "bytedance-seed/seed-2.0-mini": [
    "text",
    "image",
    "video"
  ],
  "google/gemini-3.1-flash-image-preview": [
    "image",
    "text"
  ],
  "qwen/qwen3.5-35b-a3b": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.5-27b": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.5-122b-a10b": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.5-flash-02-23": [
    "text",
    "image",
    "video"
  ],
  "google/gemini-3.1-pro-preview-customtools": [
    "text",
    "audio",
    "image",
    "video",
    "file"
  ],
  "openai/gpt-5.3-codex": [
    "text",
    "image",
    "file"
  ],
  "google/gemini-3.1-pro-preview": [
    "audio",
    "file",
    "image",
    "text",
    "video"
  ],
  "anthropic/claude-sonnet-4.6": [
    "text",
    "image"
  ],
  "qwen/qwen3.5-plus-02-15": [
    "text",
    "image",
    "video"
  ],
  "qwen/qwen3.5-397b-a17b": [
    "text",
    "image",
    "video"
  ],
  "anthropic/claude-opus-4.6": [
    "text",
    "image"
  ],
  "openrouter/free": [
    "text",
    "image"
  ],
  "moonshotai/kimi-k2.5": [
    "text",
    "image"
  ],
  "openai/gpt-audio": [
    "text",
    "audio"
  ],
  "openai/gpt-audio-mini": [
    "text",
    "audio"
  ],
  "openai/gpt-5.2-codex": [
    "text",
    "image"
  ],
  "bytedance-seed/seed-1.6-flash": [
    "image",
    "text",
    "video"
  ],
  "bytedance-seed/seed-1.6": [
    "image",
    "text",
    "video"
  ],
  "google/gemini-3-flash-preview": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "openai/gpt-5.2-chat": [
    "file",
    "image",
    "text"
  ],
  "openai/gpt-5.2-pro": [
    "image",
    "text",
    "file"
  ],
  "openai/gpt-5.2": [
    "file",
    "image",
    "text"
  ],
  "z-ai/glm-4.6v": [
    "image",
    "text",
    "video"
  ],
  "openai/gpt-5.1-codex-max": [
    "text",
    "image"
  ],
  "amazon/nova-2-lite-v1": [
    "text",
    "image",
    "video",
    "file"
  ],
  "mistralai/ministral-14b-2512": [
    "text",
    "image"
  ],
  "mistralai/ministral-8b-2512": [
    "text",
    "image"
  ],
  "mistralai/ministral-3b-2512": [
    "text",
    "image"
  ],
  "mistralai/mistral-large-2512": [
    "text",
    "image"
  ],
  "anthropic/claude-opus-4.5": [
    "file",
    "image",
    "text"
  ],
  "google/gemini-3-pro-image-preview": [
    "image",
    "text"
  ],
  "x-ai/grok-4.1-fast": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-5.1": [
    "image",
    "text",
    "file"
  ],
  "openai/gpt-5.1-chat": [
    "file",
    "image",
    "text"
  ],
  "openai/gpt-5.1-codex": [
    "text",
    "image"
  ],
  "openai/gpt-5.1-codex-mini": [
    "image",
    "text"
  ],
  "amazon/nova-premier-v1": [
    "text",
    "image"
  ],
  "perplexity/sonar-pro-search": [
    "text",
    "image"
  ],
  "mistralai/voxtral-small-24b-2507": [
    "text",
    "audio"
  ],
  "nvidia/nemotron-nano-12b-v2-vl:free": [
    "image",
    "text",
    "video"
  ],
  "nvidia/nemotron-nano-12b-v2-vl": [
    "image",
    "text",
    "video"
  ],
  "qwen/qwen3-vl-32b-instruct": [
    "text",
    "image"
  ],
  "openai/gpt-5-image-mini": [
    "file",
    "image",
    "text"
  ],
  "anthropic/claude-haiku-4.5": [
    "image",
    "text"
  ],
  "qwen/qwen3-vl-8b-thinking": [
    "image",
    "text"
  ],
  "qwen/qwen3-vl-8b-instruct": [
    "image",
    "text"
  ],
  "openai/gpt-5-image": [
    "image",
    "text",
    "file"
  ],
  "openai/o3-deep-research": [
    "image",
    "text",
    "file"
  ],
  "openai/o4-mini-deep-research": [
    "file",
    "image",
    "text"
  ],
  "google/gemini-2.5-flash-image": [
    "image",
    "text"
  ],
  "qwen/qwen3-vl-30b-a3b-thinking": [
    "text",
    "image"
  ],
  "qwen/qwen3-vl-30b-a3b-instruct": [
    "text",
    "image"
  ],
  "openai/gpt-5-pro": [
    "image",
    "text",
    "file"
  ],
  "anthropic/claude-sonnet-4.5": [
    "text",
    "image",
    "file"
  ],
  "google/gemini-2.5-flash-lite-preview-09-2025": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "qwen/qwen3-vl-235b-a22b-thinking": [
    "text",
    "image"
  ],
  "qwen/qwen3-vl-235b-a22b-instruct": [
    "text",
    "image"
  ],
  "openai/gpt-5-codex": [
    "text",
    "image"
  ],
  "x-ai/grok-4-fast": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4o-audio-preview": [
    "audio",
    "text"
  ],
  "mistralai/mistral-medium-3.1": [
    "text",
    "image"
  ],
  "baidu/ernie-4.5-vl-28b-a3b": [
    "text",
    "image"
  ],
  "z-ai/glm-4.5v": [
    "text",
    "image"
  ],
  "openai/gpt-5-chat": [
    "file",
    "image",
    "text"
  ],
  "openai/gpt-5": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-5-mini": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-5-nano": [
    "text",
    "image",
    "file"
  ],
  "anthropic/claude-opus-4.1": [
    "image",
    "text",
    "file"
  ],
  "bytedance/ui-tars-1.5-7b": [
    "image",
    "text"
  ],
  "google/gemini-2.5-flash-lite": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "x-ai/grok-4": [
    "image",
    "text",
    "file"
  ],
  "baidu/ernie-4.5-vl-424b-a47b": [
    "image",
    "text"
  ],
  "mistralai/mistral-small-3.2-24b-instruct": [
    "image",
    "text"
  ],
  "google/gemini-2.5-flash": [
    "file",
    "image",
    "text",
    "audio",
    "video"
  ],
  "google/gemini-2.5-pro": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "openai/o3-pro": [
    "text",
    "file",
    "image"
  ],
  "google/gemini-2.5-pro-preview": [
    "file",
    "image",
    "text",
    "audio"
  ],
  "anthropic/claude-opus-4": [
    "image",
    "text",
    "file"
  ],
  "anthropic/claude-sonnet-4": [
    "image",
    "text",
    "file"
  ],
  "mistralai/mistral-medium-3": [
    "text",
    "image"
  ],
  "google/gemini-2.5-pro-preview-05-06": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "arcee-ai/spotlight": [
    "image",
    "text"
  ],
  "meta-llama/llama-guard-4-12b": [
    "image",
    "text"
  ],
  "openai/o4-mini-high": [
    "image",
    "text",
    "file"
  ],
  "openai/o3": [
    "image",
    "text",
    "file"
  ],
  "openai/o4-mini": [
    "image",
    "text",
    "file"
  ],
  "openai/gpt-4.1": [
    "image",
    "text",
    "file"
  ],
  "openai/gpt-4.1-mini": [
    "image",
    "text",
    "file"
  ],
  "openai/gpt-4.1-nano": [
    "image",
    "text",
    "file"
  ],
  "meta-llama/llama-4-maverick": [
    "text",
    "image"
  ],
  "meta-llama/llama-4-scout": [
    "text",
    "image"
  ],
  "openai/o1-pro": [
    "text",
    "image",
    "file"
  ],
  "mistralai/mistral-small-3.1-24b-instruct": [
    "text",
    "image"
  ],
  "google/gemma-3-4b-it:free": [
    "text",
    "image"
  ],
  "google/gemma-3-4b-it": [
    "text",
    "image"
  ],
  "google/gemma-3-12b-it:free": [
    "text",
    "image"
  ],
  "google/gemma-3-12b-it": [
    "text",
    "image"
  ],
  "google/gemma-3-27b-it:free": [
    "text",
    "image"
  ],
  "google/gemma-3-27b-it": [
    "text",
    "image"
  ],
  "perplexity/sonar-reasoning-pro": [
    "text",
    "image"
  ],
  "perplexity/sonar-pro": [
    "text",
    "image"
  ],
  "google/gemini-2.0-flash-lite-001": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "anthropic/claude-3.7-sonnet": [
    "text",
    "image",
    "file"
  ],
  "anthropic/claude-3.7-sonnet:thinking": [
    "text",
    "image",
    "file"
  ],
  "openai/o3-mini-high": [
    "text",
    "file"
  ],
  "google/gemini-2.0-flash-001": [
    "text",
    "image",
    "file",
    "audio",
    "video"
  ],
  "qwen/qwen-vl-plus": [
    "text",
    "image"
  ],
  "qwen/qwen-vl-max": [
    "text",
    "image"
  ],
  "qwen/qwen2.5-vl-72b-instruct": [
    "text",
    "image"
  ],
  "openai/o3-mini": [
    "text",
    "file"
  ],
  "perplexity/sonar": [
    "text",
    "image"
  ],
  "minimax/minimax-01": [
    "text",
    "image"
  ],
  "openai/o1": [
    "text",
    "image",
    "file"
  ],
  "amazon/nova-lite-v1": [
    "text",
    "image"
  ],
  "amazon/nova-pro-v1": [
    "text",
    "image"
  ],
  "openai/gpt-4o-2024-11-20": [
    "text",
    "image",
    "file"
  ],
  "mistralai/pixtral-large-2411": [
    "text",
    "image"
  ],
  "anthropic/claude-3.5-haiku": [
    "text",
    "image"
  ],
  "meta-llama/llama-3.2-11b-vision-instruct": [
    "text",
    "image"
  ],
  "openai/gpt-4o-2024-08-06": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4o-mini-2024-07-18": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4o-mini": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4o-2024-05-13": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4o": [
    "text",
    "image",
    "file"
  ],
  "openai/gpt-4-turbo": [
    "text",
    "image"
  ],
  "anthropic/claude-3-haiku": [
    "text",
    "image"
  ],
  "openrouter/auto": [
    "text",
    "image",
    "audio",
    "file",
    "video"
  ]
};
